# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 步步宝2

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        bbb_ck: ${{ secrets.bbb_ck }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/q154327/TaskAction.git ~/TaskAction
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.bbb_ck
        run: |
          cd ~/TaskAction
          npm install
      - name: '运行 【步步宝2】'
        if: env.bbb_ck
        run: |
          cd ~/TaskAction
          node workflow/BBB2.js
