# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 笑谱

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 8-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER }}
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        XP_CASH: ${{ secrets.XP_CASH }}
        XP_live: ${{ secrets.XP_live }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/q154327/TaskAction.git ~/TaskAction
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/TaskAction
          npm install
      - name: '运行 【笑谱】'
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/TaskAction
          node workflow/iboxpay.js

    
