# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 燃旅视频

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        RLURL: ${{ secrets.RLURL }}
        RLHEADER: ${{ secrets.RLHEADER }}
        RLBODY: ${{ secrets.RLBODY }}
        RLURL1: ${{ secrets.RLURL1 }}
        RLHEADER1: ${{ secrets.RLHEADER1 }}
        RLBODY1: ${{ secrets.RLBODY1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【燃旅视频1】'
        if: env.RLHEADER
        run: |
          node workflow/ranlv.js
        env:
          RLURL: ${{ secrets.RLURL }}
          RLHEADER: ${{ secrets.RLHEADER }}
          RLBODY: ${{ secrets.RLBODY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          
      - name: '运行 【燃旅视频2】'
        if: env.RLHEADER1
        run: |
          node workflow/ranlv.js
        env:
          RLURL: ${{ secrets.RLURL1 }}
          RLHEADER: ${{ secrets.RLHEADER1 }}
          RLBODY: ${{ secrets.RLBODY1 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
