# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# 每日早9点到晚8点每2小时运行一次

name: 中青浏览赚

on:
  workflow_dispatch:
  schedule:
     - cron: '8 */2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_START: ${{ secrets.YOUTH_START }}
      YOUTH_READ2: ${{ secrets.YOUTH_END }}
      TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点浏览赚】'
        if: env.YOUTH_START
        run: |
          node workflow/youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START }}
          YOUTH_READ2: ${{ secrets.YOUTH_END }}
